# Generated by Django 3.2.18 on 2024-06-05 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0056_alter_organization_map_help_text'),
        ('helpdesk', '0102_add_kbitem_unlisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbitem',
            name='unlisted',
            field=models.BooleanField(default=False, help_text='Should this form be hidden from the public article list? (If the "Is this article publicly visible?" option is checked, this form will still be accessible by everyone through the link.)', verbose_name='Unlisted'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('delete_by', models.DateTimeField()),
                ('announcement', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.ticket', verbose_name='Ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
