# Generated by Django 3.2.20 on 2024-09-17 14:17

from django.db import migrations, models
import django.db.models.deletion


def assign_default_org_to_saved_search(apps, schema_editor):
    SavedSearch = apps.get_model('helpdesk', 'SavedSearch')
    
    for saved_search in SavedSearch.objects.all():
        saved_search.organization = saved_search.user.default_organization
        saved_search.save()

class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0061_add_org_backgroundimage'),
        ('helpdesk', '0102_add_kbitem_unlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.organization', verbose_name='Organization'),
        ),
        migrations.RunPython(assign_default_org_to_saved_search, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='savedsearch',
            name='organization',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='orgs.organization', verbose_name='Organization')
        )
    ]
