# Generated by Django 3.2.18 on 2024-06-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0103_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='enable_notifications',
            field=models.BooleanField(default=True, help_text="Get notifications when tickets you've been assigned to or CC'd on are updated?", verbose_name='Enable notification when tickets are created or updated?'),
        ),
    ]
