# Generated by Django 3.2.18 on 2024-08-13 15:39

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0104_alter_usersettings_model'),
    ]

    operations = [
        TrigramExtension()
    ]
    
    
