# Generated by Django 3.2.18 on 2024-10-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0105_disallow_null_savedsearch_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependsOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_alert_text', models.TextField(blank=True, help_text='Shown to the User in the Parent CustomField when it has a specific value', null=True, verbose_name='Parent Alert Text')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Comparison Value')),
                ('dependent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_fields', to='helpdesk.customfield')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_fields', to='helpdesk.customfield')),
            ],
        ),
    ]
