# Generated by Django 3.2.20 on 2024-10-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0105_disallow_null_savedsearch_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsearch',
            name='opted_out_users',
        ),
        migrations.RemoveField(
            model_name='savedsearch',
            name='shared',
        ),
    ]
