# Generated by Django 3.2.20 on 2024-12-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0105_disallow_null_savedsearch_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtype',
            name='auto_copy',
            field=models.BooleanField(default=False, help_text='Should form submissions automatically copy data to the paired BEAM property or tax lot?', verbose_name='Automatically Copy to Beam'),
        ),
        migrations.AddField(
            model_name='formtype',
            name='auto_pair',
            field=models.BooleanField(default=False, help_text='Should form submissions automatically attempt to pair with the BEAM inventory?', verbose_name='Automatically Pair'),
        ),
        migrations.AddConstraint(
            model_name='formtype',
            constraint=models.CheckConstraint(check=models.Q(('auto_copy', False), models.Q(('auto_copy', True), ('auto_pair', True)), _connector='OR'), name='form_auto_pair_if_auto_copy'),
        ),
    ]
