# Generated by Django 3.2.20 on 2025-01-08 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0269_alter_event_cycle'),
        ('helpdesk', '0106_dependson'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='read_only',
            field=models.BooleanField(default=False, help_text='Prevent the user from editing this field - useful for showing prepopulated data.', verbose_name='Read Only'),
        ),
        migrations.AddField(
            model_name='formtype',
            name='prepopulate',
            field=models.BooleanField(default=False, help_text='Should this form allow prepopulation from a building ID?', verbose_name='Prepopulate Form?'),
        ),
        migrations.AddField(
            model_name='formtype',
            name='prepopulation_cycle',
            field=models.ForeignKey(blank=True, help_text='BEAM Cycle to pull property data from. Required if prepopulate is checked.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seed.cycle'),
        ),
    ]
