# Generated by Django 3.2.20 on 2025-01-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0106_dependson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependson',
            name='value',
            field=models.TextField(blank=True, help_text='Show field when the parent has this value. Use Yes or No when the parent field is a boolean (a checkbox). Not compatible with Attachment or Key Value parent fields.', null=True, verbose_name='Expected Value'),
        ),
    ]
