# Generated by Django 3.2.20 on 2024-12-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0106_dependson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependson',
            name='dependent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_fields', to='helpdesk.customfield'),
        ),
        migrations.AlterField(
            model_name='dependson',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_fields', to='helpdesk.customfield'),
        ),
    ]
