# Generated by Django 3.2.20 on 2025-01-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0109_derived_column_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtype',
            name='multi_pair',
            field=models.BooleanField(default=False, help_text='Should this form allow inputting and pairing multiple building IDs?', verbose_name='Multi-Property Pairing'),
        ),
        migrations.AddConstraint(
            model_name='formtype',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('multi_pair', True), ('prepopulate', False)), models.Q(('multi_pair', False), ('prepopulate', True)), _connector='OR'), name='multi_pair_xor_prepopulate'),
        ),
    ]
