# Generated by Django 3.2.20 on 2025-02-27 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0270_alter_inventorydocument_file_type'),
        ('orgs', '0066_password_update'),
        ('helpdesk', '0109_derived_column_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_settings_as_address_line_1', to='seed.column')),
                ('address_line_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_settings_as_address_line_2', to='seed.column')),
                ('building_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_settings_as_building_id', to='seed.column')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_settings_as_city', to='seed.column')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seed.cycle')),
                ('dq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seed.dataqualitycheck')),
                ('excluded_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seed.dataqualitystatus')),
                ('label_not_paid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_settings_not_paid', to='seed.statuslabel')),
                ('label_paid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_settings_paid', to='seed.statuslabel')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_settings_as_state', to='seed.column')),
                ('zip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_settings_as_zip', to='seed.column')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_first_name', models.CharField(max_length=200, verbose_name='Payer First Name')),
                ('payer_last_name', models.CharField(max_length=200, verbose_name='Payer Last Name')),
                ('payer_email', models.EmailField(max_length=300, verbose_name='Payer Email')),
                ('payer_company', models.CharField(blank=True, max_length=100, verbose_name='Payer Company')),
                ('token', models.CharField(max_length=500)),
                ('token_created', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'failed'), (2, 'success')], default=0, verbose_name='Payment Status')),
                ('attempt_count', models.IntegerField(default=0)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('building_owner_name', models.CharField(max_length=400, verbose_name='Building Owner Name')),
                ('building_owner_email', models.EmailField(max_length=300, verbose_name='Building Owner Email')),
                ('building_owner_address_line_1', models.CharField(max_length=1000, verbose_name='Address Line 1')),
                ('building_owner_address_line_2', models.CharField(blank=True, max_length=1000, verbose_name='Address Line 2')),
                ('building_owner_city', models.CharField(max_length=200, verbose_name='City')),
                ('building_owner_state', models.CharField(max_length=100, verbose_name='State')),
                ('building_owner_zip', models.CharField(max_length=50, verbose_name='Postal Code')),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(0, 'Credit Card'), (1, 'eCheck')], default=0, verbose_name='Payment Status')),
                ('message', models.JSONField(blank=True, default=dict, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
                ('properties', models.ManyToManyField(to='seed.PropertyView')),
            ],
        ),
    ]
