# Generated by Django 3.2.20 on 2025-02-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0270_alter_inventorydocument_file_type'),
        ('helpdesk', '0110_order_ordersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersettings',
            name='label_not_paid',
        ),
        migrations.RemoveField(
            model_name='ordersettings',
            name='label_paid',
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='payment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_settings_as_payment_status', to='seed.column'),
        ),
    ]
