# Generated by Django 3.2.20 on 2025-01-29 18:55

from django.db import migrations, models

def preprocess_ticket_building_id(apps, schema_editor):
    """
    Preprocess ticket `building_id` values that would not pass JSON encoding

    Currently:
    - replace empty strings with null values
    """
    Ticket = apps.get_model('helpdesk', 'Ticket')

    for ticket in Ticket.objects.filter(building_id__isnull=False):
        if ticket.building_id == '':
            ticket.building_id = None
            ticket.save()

class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0110_multi_pair'),
    ]

    operations = [
        migrations.RunPython(preprocess_ticket_building_id, migrations.RunPython.noop)
    ]
