# Generated by Django 3.2.20 on 2025-01-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0110_multi_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='building_id',
            field=models.JSONField(blank=True, null=True, verbose_name='Building ID'),
        ),
    ]
