# Generated by Django 3.2.20 on 2025-02-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0270_alter_inventorydocument_file_type'),
        ('helpdesk', '0111_remove_ordersettings_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersettings',
            name='building_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_settings_as_building_name', to='seed.column'),
        ),
    ]
