# Generated by Django 3.2.20 on 2025-02-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0113_building_id_from_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='beam_portfolio',
            field=models.ManyToManyField(blank=True, related_name='helpdesk_ticket', to='seed.Portfolio', verbose_name='BEAM Portfolio'),
        ),
    ]
