# Generated by Django 3.2.20 on 2025-02-04 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0273_create_portfolio_columns'),
        ('helpdesk', '0114_ticket_beam_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtype',
            name='push_cycle',
            field=models.ForeignKey(blank=True, help_text='BEAM Cycle to push property data to. Required if automatically copying data or creating portfolios.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_forms', to='seed.cycle'),
        ),
        migrations.AlterField(
            model_name='formtype',
            name='pull_cycle',
            field=models.ForeignKey(blank=True, help_text='BEAM Cycle to pull property data from. Required if prepopulate is checked or using derived column fields.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pull_forms', to='seed.cycle'),
        ),
    ]
